from enum import Enum

class UserRole(str, Enum):
    ADMINISTRATOR = "ADMINISTRATOR"
    DISTRIBUTOR = "DISTRIBUTOR"
    CLIENT = "CLIENT"
    ALUMNO = "ALUMNO"
    ALL = "ALL"

class LeadStatus(str, Enum):
    NEW = "NEW"
    CONTACTED = "CONTACTED"
    QUALIFIED = "QUALIFIED"
    UNQUALIFIED = "UNQUALIFIED"
    MEETING_PENDING = "MEETING_PENDING"
    MEETING_SCHEDULED = "MEETING_SCHEDULED"
    MEETING_COMPLETED = "MEETING_COMPLETED"
    FOLLOW_UP = "FOLLOW_UP"
    CONVERTED = "CONVERTED"
    CUSTOMER = "CUSTOMER"
    NOT_INTERESTED = "NOT_INTERESTED"
    LOST = "LOST"
    ARCHIVED = "ARCHIVED"

class Interest(str, Enum):
    HEALTHY_HABITS = "HEALTHY_HABITS"
    WELLNESS = "WELLNESS"
    GENERAL_NUTRITION = "GENERAL_NUTRITION"
    PERSONAL_ORGANIZATION = "PERSONAL_ORGANIZATION"
    PERSONAL_DEVELOPMENT = "PERSONAL_DEVELOPMENT"
    PROFESSIONAL_DEVELOPMENT = "PROFESSIONAL_DEVELOPMENT"
    BUSINESS_OPPORTUNITY = "BUSINESS_OPPORTUNITY"
    OTHER = "OTHER"

class LeadObjective(str, Enum):
    LOSE_WEIGHT = "LOSE_WEIGHT"
    GAIN_WEIGHT = "GAIN_WEIGHT"
    HABITS = "HABITS"
    SPORTS = "SPORTS"
    ENERGY = "ENERGY"
    BUSINESS = "BUSINESS"
    OTHER = "OTHER"

class Source(str, Enum):
    FACEBOOK = "FACEBOOK"
    INSTAGRAM = "INSTAGRAM"
    META_ADS = "META_ADS"
    GOOGLE = "GOOGLE"
    LINKEDIN = "LINKEDIN"
    TIKTOK = "TIKTOK"
    YOUTUBE = "YOUTUBE"
    WEBSITE = "WEBSITE"
    LANDING = "LANDING"
    ORGANIC = "ORGANIC"
    REFERRAL = "REFERRAL"
    WHATSAPP = "WHATSAPP"
    EMAIL = "EMAIL"
    MANUAL = "MANUAL"
    CSV = "CSV"
    API = "API"
    OTHER = "OTHER"

class Platform(str, Enum):
    META_ADS = "META_ADS"
    GOOGLE_ADS = "GOOGLE_ADS"
    LINKEDIN_ADS = "LINKEDIN_ADS"
    TIKTOK_ADS = "TIKTOK_ADS"
    ORGANIC = "ORGANIC"

class InteractionType(str, Enum):
    FORM_SUBMISSION = "FORM_SUBMISSION"
    WHATSAPP = "WHATSAPP"
    EMAIL = "EMAIL"
    PHONE = "PHONE"
    ZOOM = "ZOOM"
    CALENDLY = "CALENDLY"
    NOTE = "NOTE"
    SYSTEM = "SYSTEM"
    STATUS_CHANGE = "STATUS_CHANGE"
    FOLLOW_UP = "FOLLOW_UP"
    OTHER = "OTHER"

class MeetingStatus(str, Enum):
    SCHEDULED = "SCHEDULED"
    CONFIRMED = "CONFIRMED"
    COMPLETED = "COMPLETED"
    NO_SHOW = "NO_SHOW"
    CANCELLED = "CANCELLED"
    RESCHEDULED = "RESCHEDULED"

class FollowUpStatus(str, Enum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    SKIPPED = "SKIPPED"
    CANCELLED = "CANCELLED"

class AutomationEvent(str, Enum):
    LEAD_CREATED = "LEAD_CREATED"
    LEAD_CONTACTED = "LEAD_CONTACTED"
    LEAD_QUALIFIED = "LEAD_QUALIFIED"
    MEETING_SCHEDULED = "MEETING_SCHEDULED"
    MEETING_COMPLETED = "MEETING_COMPLETED"
    NO_SHOW = "NO_SHOW"
    FOLLOW_UP_DUE = "FOLLOW_UP_DUE"
    LEAD_CONVERTED = "LEAD_CONVERTED"
    CUSTOMER_CREATED = "CUSTOMER_CREATED"
