import {
  Account,
  ActivityLogItem,
  Agent,
  AgentLog,
  BrokerConnection,
  DockerContainer,
  DocumentIndex,
  ForgeDeployment,
  ForgePlugin,
  ForgeTemplate,
  GiteaMetrics,
  InfraOverview,
  KnowledgeBaseDoc,
  KpiItem,
  MinioMetrics,
  N8nMetrics,
  Position,
  PostgresMetrics,
  PrdProject,
  RagQueryResult,
  RedisMetrics,
  ServiceHealth,
  SystemSettings,
  Trade,
  TradingBot,
  VectorStoreStatus,
} from '@/types';

// ==========================================
// 1. DASHBOARD KPIS & ACTIVITY FEED
// ==========================================
export const MOCK_KPIS: KpiItem[] = [
  {
    id: 'kpi-1',
    title: 'Active Trading Bots',
    value: '14 / 16',
    change: 12.5,
    changeType: 'increase',
    timeframe: 'vs last 24h',
    subtext: '$142,850 Total Portfolio Equity',
    sparkline: [40, 45, 42, 48, 52, 58, 65, 72, 70, 78],
    category: 'trading',
  },
  {
    id: 'kpi-2',
    title: 'System CPU Load',
    value: '24.8%',
    change: -4.2,
    changeType: 'decrease',
    timeframe: 'vs avg load',
    subtext: '8 Core Cluster • 16.2 GB / 64 GB RAM',
    sparkline: [35, 30, 28, 32, 29, 25, 26, 24, 25, 24],
    category: 'system',
  },
  {
    id: 'kpi-3',
    title: 'Knowledge Nodes (RAG)',
    value: '1,420',
    change: 18.3,
    changeType: 'increase',
    timeframe: 'indexed docs',
    subtext: '512-dim Qdrant Vector Store',
    sparkline: [100, 110, 125, 140, 160, 175, 190, 210],
    category: 'research',
  },
  {
    id: 'kpi-4',
    title: 'Active AI Agents',
    value: '8 Fleet',
    change: 0.0,
    changeType: 'neutral',
    timeframe: 'all operational',
    subtext: 'Avg Latency: 42ms • 99.98% uptime',
    sparkline: [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
    category: 'agents',
  },
];

export const MOCK_ACTIVITIES: ActivityLogItem[] = [
  {
    id: 'act-1',
    timestamp: '10:42:15 UTC',
    source: 'TRADING_ENGINE',
    level: 'EXEC',
    message: 'Grid Alpha Bot executed BUY order on BTC/USDT at $68,420.50 (0.25 BTC)',
    details: { orderId: 'ord-88321', fee: '$0.42' },
  },
  {
    id: 'act-2',
    timestamp: '10:41:02 UTC',
    source: 'RESEARCH_RAG',
    level: 'INFO',
    message: 'Vector store indexed 14 new research papers on Transformer Alpha Models',
    details: { vectorsAdded: 412, latencyMs: 128 },
  },
  {
    id: 'act-3',
    timestamp: '10:39:48 UTC',
    source: 'AGENT_FLEET',
    level: 'INFO',
    message: 'Agent [Quant-Analyst-01] generated updated risk summary report',
  },
  {
    id: 'act-4',
    timestamp: '10:35:10 UTC',
    source: 'INFRASTRUCTURE',
    level: 'WARN',
    message: 'PostgreSQL connection pool hit 82% capacity threshold',
    details: { activeConn: 41, maxConn: 50 },
  },
  {
    id: 'act-5',
    timestamp: '10:28:00 UTC',
    source: 'FORGE_DEPLOY',
    level: 'EXEC',
    message: 'Successfully deployed Sentiment-Arbitrage strategy plugin v2.4.1',
  },
];

// ==========================================
// 2. TRADING MOCK DATA
// ==========================================
export const MOCK_ACCOUNT: Account = {
  id: 'acc-main',
  totalEquityUsd: 142850.45,
  cashUsd: 58200.10,
  unrealizedPnlUsd: 3420.85,
  dailyPnlUsd: 1240.50,
  dailyPnlPercent: 0.88,
  sharpeRatio: 2.84,
  profitFactor: 1.92,
  maxDrawdownPercent: 4.15,
};

export const MOCK_BROKERS: BrokerConnection[] = [
  {
    id: 'brk-1',
    broker: 'Binance',
    accountName: 'Binance Corporate Spot/Futures',
    status: 'online',
    pingMs: 18,
    apiKeyMasked: 'vm84...92xL',
    balanceUsd: 84250.00,
    environment: 'live',
    lastSync: '10s ago',
  },
  {
    id: 'brk-2',
    broker: 'Interactive Brokers',
    accountName: 'IBKR Pro Institutional',
    status: 'online',
    pingMs: 45,
    apiKeyMasked: 'ibkr_sec_...481',
    balanceUsd: 42100.45,
    environment: 'live',
    lastSync: '25s ago',
  },
  {
    id: 'brk-3',
    broker: 'Alpaca',
    accountName: 'Alpaca Paper Trading Account',
    status: 'online',
    pingMs: 32,
    apiKeyMasked: 'PK928...411A',
    balanceUsd: 16500.00,
    environment: 'paper',
    lastSync: '5s ago',
  },
  {
    id: 'brk-4',
    broker: 'Bybit',
    accountName: 'Bybit Derivatives Vault',
    status: 'degraded',
    pingMs: 142,
    apiKeyMasked: 'bybit_key_...901',
    balanceUsd: 0.00,
    environment: 'testnet',
    lastSync: '2m ago',
  },
];

export const MOCK_TRADING_BOTS: TradingBot[] = [
  {
    id: 'bot-1',
    name: 'BTC Alpha Grid v4',
    pair: 'BTC/USDT',
    strategy: 'High-Freq Grid Arbitrage',
    status: 'active',
    pnlDailyUsd: 480.20,
    pnlDailyPercent: 1.42,
    totalTrades: 342,
    winRate: 68.4,
    uptime: '14d 6h',
    maxDrawdownPercent: 2.1,
    broker: 'Binance',
  },
  {
    id: 'bot-2',
    name: 'ETH Momentum Breakout',
    pair: 'ETH/USDT',
    strategy: 'Trend Following Dual MA',
    status: 'active',
    pnlDailyUsd: 310.50,
    pnlDailyPercent: 0.95,
    totalTrades: 89,
    winRate: 62.1,
    uptime: '21d 12h',
    maxDrawdownPercent: 3.4,
    broker: 'Binance',
  },
  {
    id: 'bot-3',
    name: 'SOL Statistical Mean Reversion',
    pair: 'SOL/USDT',
    strategy: 'Bollinger Band Spreads',
    status: 'paused',
    pnlDailyUsd: -45.10,
    pnlDailyPercent: -0.22,
    totalTrades: 120,
    winRate: 54.0,
    uptime: '5d 2h',
    maxDrawdownPercent: 4.8,
    broker: 'Binance',
  },
  {
    id: 'bot-4',
    name: 'SPY Institutional HFT',
    pair: 'SPY',
    strategy: 'Options Volatility Arbitrage',
    status: 'active',
    pnlDailyUsd: 494.90,
    pnlDailyPercent: 1.15,
    totalTrades: 512,
    winRate: 74.8,
    uptime: '45d 1h',
    maxDrawdownPercent: 1.2,
    broker: 'Interactive Brokers',
  },
];

export const MOCK_POSITIONS: Position[] = [
  {
    id: 'pos-1',
    symbol: 'BTC/USDT',
    side: 'BUY',
    size: 1.25,
    entryPrice: 67200.0,
    markPrice: 68420.5,
    unrealizedPnlUsd: 1525.62,
    unrealizedPnlPercent: 1.81,
    leverage: 3,
    liquidationPrice: 48500.0,
    broker: 'Binance',
  },
  {
    id: 'pos-2',
    symbol: 'ETH/USDT',
    side: 'BUY',
    size: 15.0,
    entryPrice: 3450.0,
    markPrice: 3512.2,
    unrealizedPnlUsd: 933.0,
    unrealizedPnlPercent: 1.80,
    leverage: 2,
    liquidationPrice: 2100.0,
    broker: 'Binance',
  },
  {
    id: 'pos-3',
    symbol: 'NVDA',
    side: 'BUY',
    size: 50,
    entryPrice: 118.5,
    markPrice: 124.2,
    unrealizedPnlUsd: 285.0,
    unrealizedPnlPercent: 4.81,
    leverage: 1,
    liquidationPrice: 0,
    broker: 'Interactive Brokers',
  },
];

export const MOCK_TRADES: Trade[] = [
  {
    id: 'trd-101',
    timestamp: '10:42:15',
    botId: 'bot-1',
    botName: 'BTC Alpha Grid v4',
    symbol: 'BTC/USDT',
    side: 'BUY',
    amount: 0.25,
    price: 68420.5,
    pnlUsd: 45.2,
    feeUsd: 0.42,
    status: 'filled',
  },
  {
    id: 'trd-102',
    timestamp: '10:38:00',
    botId: 'bot-2',
    botName: 'ETH Momentum Breakout',
    symbol: 'ETH/USDT',
    side: 'SELL',
    amount: 2.5,
    price: 3512.2,
    pnlUsd: 128.4,
    feeUsd: 0.88,
    status: 'filled',
  },
  {
    id: 'trd-103',
    timestamp: '10:30:12',
    botId: 'bot-4',
    botName: 'SPY Institutional HFT',
    symbol: 'SPY',
    side: 'BUY',
    amount: 20,
    price: 554.1,
    feeUsd: 0.15,
    status: 'filled',
  },
];

// ==========================================
// 3. AGENTS MOCK DATA
// ==========================================
export const MOCK_AGENTS: Agent[] = [
  {
    id: 'agt-1',
    name: 'Quant-Analyst-Alpha',
    role: 'Quantitative Alpha Generator & Market Screener',
    model: 'claude-3-5-sonnet',
    status: 'running',
    uptime: '18d 4h',
    metrics: {
      cpuUsagePercent: 14.2,
      memoryUsageMb: 1240,
      maxMemoryMb: 4096,
      tasksCompleted: 4820,
      tasksFailed: 2,
      avgLatencyMs: 38,
    },
    lastActive: 'Just now',
    version: '2.1.0',
    tags: ['Trading', 'Alpha', 'LLM'],
  },
  {
    id: 'agt-2',
    name: 'Risk-Sentinel-01',
    role: 'Real-time Portfolio Exposure & Stop-Loss Monitor',
    model: 'gpt-4o-mini',
    status: 'running',
    uptime: '42d 12h',
    metrics: {
      cpuUsagePercent: 8.5,
      memoryUsageMb: 850,
      maxMemoryMb: 2048,
      tasksCompleted: 14200,
      tasksFailed: 0,
      avgLatencyMs: 12,
    },
    lastActive: 'Just now',
    version: '1.8.4',
    tags: ['Risk', 'Guardrails', 'HFT'],
  },
  {
    id: 'agt-3',
    name: 'Research-RAG-Indexer',
    role: 'Document Ingestion & Embedding Generator',
    model: 'text-embedding-3-large',
    status: 'thinking',
    uptime: '5d 18h',
    metrics: {
      cpuUsagePercent: 48.6,
      memoryUsageMb: 3120,
      maxMemoryMb: 8192,
      tasksCompleted: 940,
      tasksFailed: 5,
      avgLatencyMs: 145,
    },
    lastActive: 'Just now',
    version: '3.0.1',
    tags: ['VectorDB', 'RAG', 'Embeddings'],
  },
  {
    id: 'agt-4',
    name: 'Sentiment-News-Miner',
    role: 'Financial News & Macro Sentiment Scraper',
    model: 'gemini-1.5-flash',
    status: 'idle',
    uptime: '12d 2h',
    metrics: {
      cpuUsagePercent: 2.1,
      memoryUsageMb: 540,
      maxMemoryMb: 2048,
      tasksCompleted: 1850,
      tasksFailed: 1,
      avgLatencyMs: 88,
    },
    lastActive: '5m ago',
    version: '1.4.0',
    tags: ['Scraper', 'NLP', 'Sentiment'],
  },
];

export const MOCK_AGENT_LOGS: AgentLog[] = [
  {
    id: 'log-1',
    agentId: 'agt-1',
    agentName: 'Quant-Analyst-Alpha',
    timestamp: '10:44:01.120',
    level: 'INFO',
    message: 'Evaluated 120 market orderbooks. Top alpha score: BTC/USDT (0.89 confidence)',
  },
  {
    id: 'log-2',
    agentId: 'agt-2',
    agentName: 'Risk-Sentinel-01',
    timestamp: '10:43:55.800',
    level: 'INFO',
    message: 'Portfolio VaR (99% 1-day) check passed: 1.45% (Limit: 3.50%)',
  },
  {
    id: 'log-3',
    agentId: 'agt-3',
    agentName: 'Research-RAG-Indexer',
    timestamp: '10:43:12.440',
    level: 'EXEC',
    message: 'Embedding vector calculation finished for [Fed_Interest_Rates_Q3.pdf] - 48 chunks',
  },
  {
    id: 'log-4',
    agentId: 'agt-4',
    agentName: 'Sentiment-News-Miner',
    timestamp: '10:40:00.000',
    level: 'WARN',
    message: 'API rate limit threshold approaching for Bloomberg News Scraper feed (85%)',
  },
];

// ==========================================
// 4. RESEARCH & RAG MOCK DATA
// ==========================================
export const MOCK_VECTOR_STORE: VectorStoreStatus = {
  provider: 'Qdrant',
  totalVectors: 1420500,
  dimensions: 1536,
  indexSizeMb: 4280,
  searchLatencyMs: 8.4,
  status: 'online',
};

export const MOCK_DOCUMENT_INDEX: DocumentIndex = {
  totalDocuments: 1420,
  indexedDocuments: 1412,
  pendingDocuments: 6,
  failedDocuments: 2,
  lastIndexedTime: '10 minutes ago',
};

export const MOCK_RESEARCH_DOCS: KnowledgeBaseDoc[] = [
  {
    id: 'doc-1',
    title: 'High_Frequency_Statistical_Arbitrage_Framework.pdf',
    category: 'Quantitative Strategy',
    fileType: 'pdf',
    sizeBytes: 4850000,
    chunkCount: 128,
    vectorIndexed: true,
    createdAt: '2026-09-15',
    updatedAt: '2026-09-15',
    tags: ['Arbitrage', 'HFT', 'OrderBook'],
  },
  {
    id: 'doc-2',
    title: 'Macroeconomic_Sentiment_LLM_Prompting.md',
    category: 'NLP Research',
    fileType: 'md',
    sizeBytes: 32000,
    chunkCount: 14,
    vectorIndexed: true,
    createdAt: '2026-09-17',
    updatedAt: '2026-09-18',
    tags: ['LLM', 'Sentiment', 'Macro'],
  },
  {
    id: 'doc-3',
    title: 'Risk_Management_Max_Drawdown_Bounds.pdf',
    category: 'Risk Engine',
    fileType: 'pdf',
    sizeBytes: 2100000,
    chunkCount: 45,
    vectorIndexed: true,
    createdAt: '2026-09-10',
    updatedAt: '2026-09-12',
    tags: ['Risk', 'Drawdown', 'VaR'],
  },
  {
    id: 'doc-4',
    title: 'Multi_Agent_Consensus_Trading_Protocols.json',
    category: 'Agent Architecture',
    fileType: 'json',
    sizeBytes: 154000,
    chunkCount: 28,
    vectorIndexed: false,
    createdAt: '2026-09-18',
    updatedAt: '2026-09-18',
    tags: ['Agents', 'Consensus'],
  },
];

export const MOCK_RAG_RESULT: RagQueryResult = {
  query: 'Optimal risk threshold for statistical arbitrage grid bots under high volatility',
  matchedChunks: [
    {
      documentTitle: 'Risk_Management_Max_Drawdown_Bounds.pdf',
      chunkId: 'chk-842',
      score: 0.94,
      snippet:
        'When market volatility exceeds 45% annualised, grid spacing must be dynamically scaled by a factor of 1.4x while maintaining a strict 3.5% portfolio stop-loss boundary.',
    },
    {
      documentTitle: 'High_Frequency_Statistical_Arbitrage_Framework.pdf',
      chunkId: 'chk-109',
      score: 0.88,
      snippet:
        'Grid order density should be reduced during low liquidity regimes to avoid slippage on order execution.',
    },
  ],
  executionTimeMs: 42,
  tokensUsed: 620,
};

// ==========================================
// 5. INFRASTRUCTURE MOCK DATA
// ==========================================
export const MOCK_SERVICES: ServiceHealth[] = [
  {
    id: 'srv-1',
    name: 'Docker',
    status: 'online',
    uptime: '45 days',
    latencyMs: 2,
    version: '27.1.1',
    port: 2375,
    url: 'unix:///var/run/docker.sock',
    metrics: { containersRunning: 12, imagesTotal: 24, cpuUsage: '18%' },
  },
  {
    id: 'srv-2',
    name: 'PostgreSQL',
    status: 'online',
    uptime: '45 days',
    latencyMs: 4,
    version: '16.3',
    port: 5432,
    url: 'postgresql://prd_admin@localhost:5432/prd_os',
    metrics: { activeConnections: 34, dbSizeMb: 1420, tps: 185 },
  },
  {
    id: 'srv-3',
    name: 'Redis',
    status: 'online',
    uptime: '45 days',
    latencyMs: 1,
    version: '7.2.4',
    port: 6379,
    url: 'redis://localhost:6379/0',
    metrics: { memoryUsedMb: 412, hitRate: '99.4%', keys: 84200 },
  },
  {
    id: 'srv-4',
    name: 'N8N',
    status: 'online',
    uptime: '18 days',
    latencyMs: 15,
    version: '1.42.0',
    port: 5678,
    url: 'http://localhost:5678',
    metrics: { activeWorkflows: 8, executionsToday: 1420 },
  },
  {
    id: 'srv-5',
    name: 'MinIO',
    status: 'online',
    uptime: '30 days',
    latencyMs: 12,
    version: 'RELEASE.2024-05',
    port: 9000,
    url: 'http://localhost:9000',
    metrics: { totalBuckets: 6, storageUsedGb: 48.2 },
  },
  {
    id: 'srv-6',
    name: 'Gitea',
    status: 'online',
    uptime: '45 days',
    latencyMs: 8,
    version: '1.22.0',
    port: 3000,
    url: 'http://localhost:3000',
    metrics: { repositories: 14, openPRs: 2 },
  },
];

export const MOCK_DOCKER_CONTAINERS: DockerContainer[] = [
  {
    id: 'c-1',
    name: 'prd-trading-engine',
    image: 'prd/trading-core:latest',
    status: 'running',
    cpuPercent: 8.4,
    memoryMb: 420,
    ports: '8080:8080',
    created: '14 days ago',
  },
  {
    id: 'c-2',
    name: 'prd-qdrant-vectordb',
    image: 'qdrant/qdrant:v1.9.0',
    status: 'running',
    cpuPercent: 12.1,
    memoryMb: 1420,
    ports: '6333:6333',
    created: '45 days ago',
  },
  {
    id: 'c-3',
    name: 'prd-postgres-db',
    image: 'postgres:16-alpine',
    status: 'running',
    cpuPercent: 4.2,
    memoryMb: 680,
    ports: '5432:5432',
    created: '45 days ago',
  },
  {
    id: 'c-4',
    name: 'prd-redis-cache',
    image: 'redis:7-alpine',
    status: 'running',
    cpuPercent: 1.1,
    memoryMb: 210,
    ports: '6379:6379',
    created: '45 days ago',
  },
];

export const MOCK_POSTGRES: PostgresMetrics = {
  activeConnections: 34,
  maxConnections: 100,
  databaseSizeMb: 1420,
  cacheHitRatioPercent: 99.8,
  tps: 185,
};

export const MOCK_REDIS: RedisMetrics = {
  usedMemoryMb: 412,
  maxMemoryMb: 2048,
  hitRatePercent: 99.4,
  connectedClients: 18,
  keysCount: 84200,
};

export const MOCK_N8N: N8nMetrics = {
  activeWorkflows: 8,
  executionsToday: 1420,
  failedExecutions: 3,
  queuedTasks: 0,
};

export const MOCK_MINIO: MinioMetrics = {
  totalBuckets: 6,
  totalObjects: 14250,
  storageUsedGb: 48.2,
  storageLimitGb: 500.0,
};

export const MOCK_GITEA: GiteaMetrics = {
  activeRepositories: 14,
  pullRequestsOpen: 2,
  buildStatus: 'online',
  diskUsedMb: 1240,
};

export const MOCK_INFRA_OVERVIEW: InfraOverview = {
  services: MOCK_SERVICES,
  dockerContainers: MOCK_DOCKER_CONTAINERS,
  postgres: MOCK_POSTGRES,
  redis: MOCK_REDIS,
  n8n: MOCK_N8N,
  minio: MOCK_MINIO,
  gitea: MOCK_GITEA,
};

// ==========================================
// 6. FORGE MOCK DATA
// ==========================================
export const MOCK_FORGE_TEMPLATES: ForgeTemplate[] = [
  {
    id: 'tmpl-1',
    name: 'Quant Alpha Grid Engine',
    description: 'High-frequency orderbook imbalance & grid trading template with dynamic spacing.',
    category: 'Quant Strategy',
    language: 'Python',
    stars: 42,
    author: 'PRD Core Team',
    tags: ['Grid', 'HFT', 'OrderBook'],
  },
  {
    id: 'tmpl-2',
    name: 'LLM Multi-Agent Consensus System',
    description: 'Autonomous multi-agent voting network for market macro analysis and execution approval.',
    category: 'AI Agent',
    language: 'TypeScript',
    stars: 88,
    author: 'Agentic Core',
    tags: ['MultiAgent', 'Consensus', 'LLM'],
  },
  {
    id: 'tmpl-3',
    name: 'Real-time News Sentiment Pipeline',
    description: 'Fast streaming NLP analysis connector for Twitter/X, Reddit, and Financial news feeds.',
    category: 'Data Pipeline',
    language: 'Python',
    stars: 31,
    author: 'Research Lab',
    tags: ['NLP', 'Sentiment', 'Streaming'],
  },
  {
    id: 'tmpl-4',
    name: 'Institutional Risk Guardrail Shield',
    description: 'Pre-trade latency circuit breaker, maximum drawdown sentinel, and margin lock.',
    category: 'Risk Shield',
    language: 'Rust',
    stars: 56,
    author: 'Risk Engineering',
    tags: ['Rust', 'Risk', 'CircuitBreaker'],
  },
];

export const MOCK_FORGE_PLUGINS: ForgePlugin[] = [
  {
    id: 'plg-1',
    name: 'Binance WebSockets API Connector',
    version: '2.4.0',
    status: 'installed',
    category: 'Exchange Interface',
    author: 'PRD Systems',
    description: 'Sub-millisecond ticker & depth stream adapter for Binance Spot & Futures.',
  },
  {
    id: 'plg-2',
    name: 'Qdrant Vector Database Adapter',
    version: '1.9.1',
    status: 'installed',
    category: 'Storage Connector',
    author: 'Qdrant Team',
    description: 'Direct high-density embedding storage & similarity search engine driver.',
  },
  {
    id: 'plg-3',
    name: 'Telegram Emergency Alerting Dispatcher',
    version: '1.2.0',
    status: 'update_available',
    category: 'Alerting',
    author: 'Community',
    description: 'Send high priority risk alerts and order execution notifications to Telegram groups.',
  },
];

export const MOCK_FORGE_DEPLOYMENTS: ForgeDeployment[] = [
  {
    id: 'dep-101',
    systemName: 'BTC Alpha Grid Bot',
    environment: 'production',
    status: 'deployed',
    version: 'v4.2.1',
    deployedAt: '2 hours ago',
    commitHash: 'a8f9c12',
  },
  {
    id: 'dep-102',
    systemName: 'RAG Knowledge Indexer',
    environment: 'production',
    status: 'deployed',
    version: 'v3.0.0',
    deployedAt: '1 day ago',
    commitHash: 'b4e2d99',
  },
  {
    id: 'dep-103',
    systemName: 'Experimental Arbitrage Shield',
    environment: 'staging',
    status: 'building',
    version: 'v0.9.4-rc',
    deployedAt: 'In progress...',
    commitHash: 'c910a34',
  },
];

// ==========================================
// 7. PROJECTS MOCK DATA
// ==========================================
export const MOCK_PROJECTS: PrdProject[] = [
  {
    id: 'prj-1',
    name: 'Alpha-V4 High Frequency Trading Core',
    code: 'ALPHA-HFT',
    description: 'Ultra low-latency C++/Python market maker algorithm for crypto spot pairs.',
    phase: 'Production',
    completionPercent: 95,
    techStack: ['Python', 'C++', 'Redis', 'Docker'],
    teamMembers: ['Alex M.', 'Elena R.'],
    updatedAt: 'Today',
    status: 'online',
  },
  {
    id: 'prj-2',
    name: 'RAG Knowledge Vector Search',
    code: 'RAG-SEARCH',
    description: 'Enterprise internal documentation indexing & semantic semantic search engine.',
    phase: 'Production',
    completionPercent: 90,
    techStack: ['TypeScript', 'Qdrant', 'Next.js', 'PostgreSQL'],
    teamMembers: ['David K.', 'Sofia L.'],
    updatedAt: 'Yesterday',
    status: 'online',
  },
  {
    id: 'prj-3',
    name: 'Multi-Agent Autonomous Supervisor',
    code: 'AGENT-SUPERVISOR',
    description: 'Orchestrator for managing LLM agents with automated retry policies & consensus governance.',
    phase: 'In Progress',
    completionPercent: 72,
    techStack: ['Python', 'LangChain', 'PostgreSQL', 'Docker'],
    teamMembers: ['Elena R.', 'Marcus V.'],
    updatedAt: '2 days ago',
    status: 'online',
  },
  {
    id: 'prj-4',
    name: 'Risk Engine v3 Circuit Breaker',
    code: 'RISK-SHIELD-V3',
    description: 'Sub-millisecond drawdown checker with automated position liquidations and broker freeze.',
    phase: 'Beta',
    completionPercent: 84,
    techStack: ['Rust', 'gRPC', 'Redis'],
    teamMembers: ['Marcus V.'],
    updatedAt: '3 days ago',
    status: 'degraded',
  },
];

// ==========================================
// 8. SETTINGS MOCK DATA
// ==========================================
export const MOCK_SETTINGS: SystemSettings = {
  systemName: 'PRD Modular OS',
  environment: 'Production Enterprise',
  themeMode: 'dark',
  debugMode: false,
  telemetryEnabled: true,
  autoBackupInterval: 'Every 6 hours',
  apiKeys: [
    {
      id: 'key-1',
      service: 'Binance API Key (Live)',
      keyMasked: 'vm84...92xL',
      status: 'active',
      updatedAt: '2026-09-01',
    },
    {
      id: 'key-2',
      service: 'Interactive Brokers Gateway',
      keyMasked: 'ibkr_sec_...481',
      status: 'active',
      updatedAt: '2026-09-05',
    },
    {
      id: 'key-3',
      service: 'Qdrant Vector DB Token',
      keyMasked: 'qdr_tok_...8821',
      status: 'active',
      updatedAt: '2026-08-15',
    },
    {
      id: 'key-4',
      service: 'OpenAI Enterprise Key',
      keyMasked: 'sk-proj-...902x',
      status: 'active',
      updatedAt: '2026-09-10',
    },
  ],
};
